import { NewsItem, TrainingSession } from './types';

export const MOCK_NEWS: NewsItem[] = [
  {
    id: '1',
    title: 'Rhythmustraining & Monatsroda',
    excerpt: 'Unser monatliches Rhythmustraining gefolgt von der großen Monatsroda. Alle Level sind willkommen!',
    category: 'Event',
    date: '2026-04-19',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
  },
  {
    id: '2',
    title: 'Trainingsupdates Frühjahr 2026',
    excerpt: 'Wichtige Informationen zu unseren Standorten und neuen Trainingszeiten für das kommende Semester.',
    category: 'Update',
    date: '2026-03-15',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
  },
  {
    id: '3',
    title: 'Semesterferien Training',
    excerpt: 'Während der Semesterferien findet ein eingeschränkter Trainingsbetrieb statt. Details hier.',
    category: 'Info',
    date: '2026-02-01',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
  },
  {
    id: '4',
    title: 'Monatsroda im März',
    excerpt: 'Unsere Roda im März war ein voller Erfolg mit vielen Gästen und toller Energie.',
    category: 'Event',
    date: '2026-03-19',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
  },
  {
    id: '5',
    title: 'Jahresauftakt Roda',
    excerpt: 'Wir starteten das Jahr mit einer kraftvollen Roda im Januar. Ein Rückblick.',
    category: 'Event',
    date: '2026-01-15',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
  },
];

export const MOCK_TRAININGS: TrainingSession[] = [
  {
    id: '1',
    name: 'Erwachsenentraining (Alle Levels)',
    coach: 'Mestre & Team',
    time: '18:00 - 20:45',
    duration: '165 min',
    intensity: 'High',
    category: 'Erwachsene',
    spots: 20,
    price: '€70/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Kröllgasse 26, 1150 Wien',
    day: 'Montag',
    note: 'Inklusive Musiktraining (18:00-19:00)',
  },
  {
    id: '2',
    name: 'Erwachsenentraining (Alle Levels)',
    coach: 'Mestre & Team',
    time: '20:00 - 22:00',
    duration: '120 min',
    intensity: 'High',
    category: 'Erwachsene',
    spots: 15,
    price: '€70/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Währinger Straße 59, 1090 Wien (WUK)',
    day: 'Dienstag',
  },
  {
    id: '3',
    name: 'Erwachsenentraining (Alle Levels)',
    coach: 'Mestre & Team',
    time: '19:00 - 20:45',
    duration: '105 min',
    intensity: 'High',
    category: 'Erwachsene',
    spots: 18,
    price: '€70/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Vorgartenstraße 95-97, 1200 Wien',
    day: 'Mittwoch',
  },
  {
    id: '4',
    name: 'Erwachsenentraining (Anfänger*innen)',
    coach: 'Team Wien',
    time: '18:00 - 20:45',
    duration: '165 min',
    intensity: 'Medium',
    category: 'Erwachsene',
    spots: 20,
    price: '€70/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Rötzergasse 2-4, 1170 Wien',
    day: 'Donnerstag',
    note: 'Inklusive Musiktraining (18:00-19:00)',
  },
  {
    id: '5',
    name: 'Erwachsenentraining (Fortgeschrittene)',
    coach: 'Mestre & Team',
    time: '18:00 - 20:45',
    duration: '165 min',
    intensity: 'Elite',
    category: 'Erwachsene',
    spots: 15,
    price: '€70/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Schweglerstraße 2, 1150 Wien',
    day: 'Donnerstag',
    note: 'Achtung: Alarmanlage ab 17:55! Zugang via Felberstraße mit Code. Kontakt: Moni (0660/3619616). Inklusive Musiktraining (18:00-19:00)',
  },
  {
    id: '6',
    name: 'Erwachsenentraining (Alle Levels)',
    coach: 'Mestre & Team',
    time: '14:30 - 17:00',
    duration: '150 min',
    intensity: 'High',
    category: 'Erwachsene',
    spots: 25,
    price: '€70/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Robert-Blum-Gasse 2, 1200 Wien',
    day: 'Samstag',
  },
  {
    id: '7',
    name: 'Kindertraining (Anfänger 6-12 J.)',
    coach: 'Maria Samba',
    time: '16:00 - 17:00',
    duration: '60 min',
    intensity: 'Medium',
    category: 'Kinder',
    spots: 12,
    price: '€35/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Vorgartenstraße 50, 1200 Wien',
    day: 'Montag',
  },
  {
    id: '8',
    name: 'Kindertraining (Fortgeschrittene 8-14 J.)',
    coach: 'Maria Samba',
    time: '17:00 - 18:00',
    duration: '60 min',
    intensity: 'High',
    category: 'Kinder',
    spots: 12,
    price: '€35/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Vorgartenstraße 50, 1200 Wien',
    day: 'Montag',
  },
  {
    id: '9',
    name: 'Kindertraining (Anfänger 6-12 J.)',
    coach: 'Maria Samba',
    time: '16:00 - 17:00',
    duration: '60 min',
    intensity: 'Medium',
    category: 'Kinder',
    spots: 12,
    price: '€35/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Vorgartenstraße 50, 1200 Wien',
    day: 'Dienstag',
  },
  {
    id: '10',
    name: 'Kindertraining (Fortgeschrittene 8-14 J.)',
    coach: 'Maria Samba',
    time: '18:00 - 19:00',
    duration: '60 min',
    intensity: 'High',
    category: 'Kinder',
    spots: 12,
    price: '€35/Mo',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Vorgartenstraße 95-97, 1200 Wien',
    day: 'Mittwoch',
  },
  {
    id: '11',
    name: 'Musiktraining (Berimbau & Gesang)',
    coach: 'Instrumentalists',
    time: '18:00 - 19:00',
    duration: '60 min',
    intensity: 'Low',
    category: 'Musik',
    spots: 25,
    price: 'Inkludiert',
    imageUrl: 'https://capoeiravienna.at/wp-content/themes/capoeiravienna/images/header-logo.png',
    location: 'Kröllgasse & Rötzergasse',
    day: 'Mo & Do',
    note: 'Findet jeweils in der ersten Stunde des Erwachsenentrainings statt.',
  },
];
